@Restaurants.API_HostAddress = https://localhost:5000



GET {{Restaurants.API_HostAddress}}/api/restaurants

###

GET {{Restaurants.API_HostAddress}}/api/restaurants/1

###

GET {{Restaurants.API_HostAddress}}/api/restaurants/1/dishes

###

GET {{Restaurants.API_HostAddress}}/api/restaurants/1/dishes/2

###

POST {{Restaurants.API_HostAddress}}/api/restaurants/6/dishes
Content-Type: application/json

{
  "Name": "Spaghetti Bolognese",
  "Description": "Classic Italian pasta dish with rich meat sauce",
  "Price": 12.99,
  "KiloCalories": 750
}

###

DELETE {{Restaurants.API_HostAddress}}/api/restaurants/6/dishes

###

POST {{Restaurants.API_HostAddress}}/api/restaurants
Content-Type: application/json

{
    "Name": "MediatR test",
    "Description": "A culinary experience like no other",
    "Category": "Italian",
    "HasDelivery": true,
    "ContactEmail": "info@gourmetdelights.com",
    "ContactNumber": "555-123-4567",
    "City": "Metropolis",
    "Street": "456 Gourmet Avenue",
    "PostalCode": "78040-300"
}

###

GET {{Restaurants.API_HostAddress}}/api/restaurants/3

###

POST {{Restaurants.API_HostAddress}}/api/restaurants
Content-Type: application/json

{
    "Name": "Tasty Bites Test 1",
    "Description": "A cozy restaurant serving a variety of delicious dishes.",
    "Category": "American",
    "HasDelivery": true,
    "ContactEmail": "info@tastybites.com",
    "ContactNumber": "1199225-7825",
    "City": "New York",
    "Street": "123 Main Street",
    "PostalCode": "79050-001"
}

###

DELETE {{Restaurants.API_HostAddress}}/api/restaurants/5

###

PATCH {{Restaurants.API_HostAddress}}/api/restaurants/6
Content-Type: application/json

{
  "Name": "Tasty Bites Test 1.1",
  "Description": "This is a sample restaurant description.",
  "HasDelivery": false
}

###

POST {{Restaurants.API_HostAddress}}/api/restaurants/2/dishes
Content-Type: application/json

{
  "Name": "Spaghetti Bolognese",
  "Description": "Classic Italian pasta dish with rich meat sauce",
  "Price": 12.99,
  "KiloCalories": 750
}

###
